/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoverImage: typeof import('./src/components/CoverImage.vue')['default']
    MusicCollection: typeof import('./src/components/MusicCollection.vue')['default']
    MusicCollectionCtrl: typeof import('./src/components/MusicCollectionCtrl.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMarquee: typeof import('naive-ui')['NMarquee']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NPopover: typeof import('naive-ui')['NPopover']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSlider: typeof import('naive-ui')['NSlider']
    NText: typeof import('naive-ui')['NText']
    PlayerCtrl: typeof import('./src/components/player/PlayerCtrl.vue')['default']
    PlayerCtrlBar: typeof import('./src/components/layouts/PlayerCtrlBar.vue')['default']
    PlayerHeader: typeof import('./src/components/layouts/PlayerHeader.vue')['default']
    PlayerInfo: typeof import('./src/components/player/PlayerInfo.vue')['default']
    PlayerListSidebar: typeof import('./src/components/layouts/PlayerListSidebar.vue')['default']
    PlayerMode: typeof import('./src/components/player/PlayerMode.vue')['default']
    PlayerModel: typeof import('./src/components/player/PlayerModel.vue')['default']
    PlayerModle: typeof import('./src/components/player/PlayerModle.vue')['default']
    PlayerVolume: typeof import('./src/components/player/PlayerVolume.vue')['default']
    PlayList: typeof import('./src/components/player/PlayList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongInfo: typeof import('./src/components/SongInfo.vue')['default']
    TextAutoMarquee: typeof import('./src/components/TextAutoMarquee.vue')['default']
    TextLoadPlaceholder: typeof import('./src/components/TextLoadPlaceholder.vue')['default']
  }
}
